Convert Master tags to data classes
matthewcmckenna/m3u8-parser pull request #1
Opened 2018-07-08 18:12 UTC by jcosentino11

2018-07-08 20:12 UTC, himattm requested changes

2018-07-08 20:12 UTC, himattm commented on src/main/kotlin/com/matthewcmckenna/github/m3u8/model/tag/Master.kt
> +    data class Start(
For constructors that go past the 120 character limit we should do separate lines, but otherwise I think we can do one line

2018-07-08 20:12 UTC, himattm commented on src/main/kotlin/com/matthewcmckenna/github/m3u8/model/tag/Master.kt
> +            val default: String?,
this isn't truly optional. its absence means it defaults to "no"

> The value is an enumerated-string; valid strings are YES and NO. If the value is YES, then the client SHOULD play this Rendition of the content in the absence of information from the user indicating a different choice.  **This attribute is OPTIONAL.  Its absence indicates an implicit value of NO.**

`val default: String = "NO"`

2018-07-08 20:12 UTC, himattm commented on src/main/kotlin/com/matthewcmckenna/github/m3u8/model/tag/Master.kt
> +            val autoselect: String?,
Same thing for this one:

>AUTOSELECT
 The value is an enumerated-string; valid strings are YES and NO. This attribute is OPTIONAL.  Its absence indicates an implicit value of NO.

2018-07-08 20:12 UTC, himattm commented on src/main/kotlin/com/matthewcmckenna/github/m3u8/model/tag/Master.kt
> +            val forced: String?,
Same for this one:

> FORCED
      The value is an enumerated-string; valid strings are YES and NO.
      This attribute is OPTIONAL.  Its absence indicates an implicit
      value of NO.

2018-07-08 20:12 UTC, himattm commented on src/main/kotlin/com/matthewcmckenna/github/m3u8/model/tag/Master.kt
> +            val bandwith: Int,
I think there could be a case (extremely long video) where the bandwidth exceeds and Int's size

2018-07-08 20:12 UTC, himattm commented on src/main/kotlin/com/matthewcmckenna/github/m3u8/model/tag/Master.kt
> +            val resolution: String?,
Same discussion about pre-parsing. If we are parsing before putting objects here we should make this

`data class Resolution(val width: Int, val height: Int)`

And then have that be the type of this param

2023-12-06 19:40 UTC, himattm commented
lol this old

2023-12-06 19:40 UTC, closed without merging

2023-12-06 19:43 UTC, jcosentino11 commented
Merge it